# Generated by Django 3.1.6 on 2021-02-21 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210220_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joined_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 12, 44, 18, 51967)),
        ),
    ]
