# Generated by Django 3.1.6 on 2021-02-24 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210221_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joined_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 11, 42, 0, 492523)),
        ),
    ]
