# Generated by Django 3.1.6 on 2021-02-28 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210224_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joined_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 19, 40, 1, 910589)),
        ),
    ]
