# Generated by Django 3.1.6 on 2021-02-28 14:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20210224_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 19, 40, 1, 910589)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_time', models.DateTimeField(default=datetime.datetime(2021, 2, 28, 19, 40, 1, 910589))),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
